/** @type {import("../pb_data/types.d.ts") */
migrate(
  (app) => {
    const collection = new Collection({
      createRule: '@request.auth.collectionName = "users"',
      deleteRule: "sender.id = @request.auth.id",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          cascadeDelete: false,
          collectionId: "_pb_users_auth_",
          hidden: false,
          id: "relation1593854671",
          maxSelect: 1,
          minSelect: 0,
          name: "sender",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          cascadeDelete: false,
          collectionId: "pbc_3614170744",
          hidden: false,
          id: "relation1745156937",
          maxSelect: 1,
          minSelect: 0,
          name: "recipient",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text1843675174",
          max: 500,
          min: 0,
          name: "description",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "date910263432",
          max: "",
          min: "",
          name: "starts_on",
          presentable: false,
          required: true,
          system: false,
          type: "date",
        },
        {
          hidden: false,
          id: "date1286299219",
          max: "",
          min: "",
          name: "ends_on",
          presentable: false,
          required: true,
          system: false,
          type: "date",
        },
        {
          hidden: false,
          id: "select2063623452",
          maxSelect: 1,
          name: "status",
          presentable: false,
          required: false,
          system: false,
          type: "select",
          values: ["pending", "accepted", "rejected", "cancelled"],
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_1037645436",
      indexes: [],
      listRule: "sender.id = @request.auth.id || recipient.id = @request.auth.id",
      name: "appointments",
      system: false,
      type: "base",
      updateRule: "sender.id = @request.auth.id || recipient.id = @request.auth.id",
      viewRule: "sender.id = @request.auth.id || recipient.id = @request.auth.id",
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_1037645436");

    return app.delete(collection);
  },
);
