/** @type {import("../pb_data/types.d.ts") */
migrate(
  (app) => {
    const collection = new Collection({
      createRule: '@request.auth.collectionName = "teachers"',
      deleteRule: "appointer.id = @request.auth.id || appointee.id = @request.auth.id",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text1579384326",
          max: 255,
          min: 3,
          name: "name",
          pattern: "^[a-z0-9_-]+$",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          cascadeDelete: true,
          collectionId: "_pb_users_auth_",
          hidden: false,
          id: "relation2921965327",
          maxSelect: 1,
          minSelect: 0,
          name: "appointer",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          cascadeDelete: true,
          collectionId: "pbc_3614170744",
          hidden: false,
          id: "relation771367624",
          maxSelect: 1,
          minSelect: 0,
          name: "appointee",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_3085411453",
      indexes: ["CREATE UNIQUE INDEX `idx_GJbuX5Jg0x` ON `rooms` (`name`)"],
      listRule: "appointer.id = @request.auth.id || appointee.id = @request.auth.id",
      name: "rooms",
      system: false,
      type: "base",
      updateRule: "appointer.id = @request.auth.id || appointee.id = @request.auth.id",
      viewRule: "appointer.id = @request.auth.id || appointee.id = @request.auth.id",
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_3085411453");

    return app.delete(collection);
  },
);
